### ISSUE TITLE
Posible bug when unfocus tab autosave is enabled

### ISSUE THREAD

**Issue by max-mykhailenko** [max-mykhailenko/memTask#10]
Trace:

```
/Users/File.php with encoding UTF-8 (atomic)
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 255, in on_post_save
    callback.on_post_save(v)
  File "memTask in /Users/username/Library/Application Support/Sublime Text 3/Installed Packages/memTask.sublime-package", line 96, in on_post_save
AttributeError: 'memTask' object has no attribute 'base'
```

**Comment by max-mykhailenko** [comment]
Now post_save will be async
