### ISSUE TITLE
memTask is not showing any data

### ISSUE THREAD

**Issue by ghost** [max-mykhailenko/memTask#11]
It might be related to: https://github.com/max-mykhailenko/memTask/issues/9
I'm using ST3 and Windows 8.1 x64.

Here is the console output:
Traceback (most recent call last):
  File "./json/decoder.py", line 368, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "memTask in C:\Users\Vali\AppData\Roaming\Sublime Text 3\Installed Packages\memTask.sublime-package", line 45, in <lambda>
  File "memTask in C:\Users\Vali\AppData\Roaming\Sublime Text 3\Installed Packages\memTask.sublime-package", line 52, in finish_init
  File "memTask in C:\Users\Vali\AppData\Roaming\Sublime Text 3\Installed Packages\memTask.sublime-package", line 121, in ReadBaseFromFile
  File "./json/__init__.py", line 274, in load
  File "./json/__init__.py", line 319, in loads
  File "./json/decoder.py", line 352, in decode
  File "./json/decoder.py", line 370, in raw_decode
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "./json/decoder.py", line 368, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "memTask in C:\Users\Vali\AppData\Roaming\Sublime Text 3\Installed Packages\memTask.sublime-package", line 45, in <lambda>
  File "memTask in C:\Users\Vali\AppData\Roaming\Sublime Text 3\Installed Packages\memTask.sublime-package", line 52, in finish_init
  File "memTask in C:\Users\Vali\AppData\Roaming\Sublime Text 3\Installed Packages\memTask.sublime-package", line 121, in ReadBaseFromFile
  File "./json/__init__.py", line 274, in load
  File "./json/__init__.py", line 319, in loads
  File "./json/decoder.py", line 352, in decode
  File "./json/decoder.py", line 370, in raw_decode
ValueError: No JSON object could be decoded

**Comment by max-mykhailenko** [comment]
@vali98n can you attach your memtask.json file?

**Comment by max-mykhailenko** [comment]
Closed as not actual. Please give me more details.
